### ISSUE TITLE
Inquiry Regarding Branches for Message Flow Analysis in ROS2 Tracing

### ISSUE THREAD

**Issue by YerayGG** [christophebedard/ros2-message-flow-analysis#1]
Dear Christophe Bedard,

I hope this message finds you well.

I am currently working with the ros2_tracing repository and have encountered a question regarding the appropriate branches to use for message flow analysis.

Specifically, I am using ROS 2 Humble and have observed that while the humble branch of ros2_tracing functions correctly within my ROS 2 Humble setup, I am experiencing difficulties with displaying graphs in Eclipse Trace Compass. On the other hand, the message-link-instrumentation branch does not work on my system with ROS 2 Humble.

Could you please clarify if it is possible to perform message flow analysis using the humble branch? the message-link-instrumentation branch is compatible with ROS 2 Humble or could potentially be made compatible in some way?

Thank you very much for your assistance.

Best regards,

Yeray Guadalcazar

**Comment by christophebedard** [comment]
Which `rmw` implementation are you using?

If you can, I would try using a newer distro, like Jazzy. That should work.

**Comment by christophebedard** [comment]
> On the other hand, the message-link-instrumentation branch does not work on my system with ROS 2 Humble.

I'm guessing you're referring to this branch? https://github.com/ros2/ros2_tracing/commits/message-link-instrumentation/ Can you explain what doesn't work exactly?

**Comment by YerayGG** [comment]
My rmw_implementation is cyclonedds.

My ros2 version is humble, unfortunately I can't change it.

I am encountering a build error when trying to build the tracetools package from the message-link-instrumentation branch of the ros2_tracing repository. The build succeeds when using the humble branch, but fails with errors when switching to the message-link-instrumentation branch.

Attempt to build the package with colcon build --packages-up-to tracetools --allow-overriding tracetools and I found the following error message:


$ colcon build --packages-up-to tracetools --allow-overriding tracetools
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/tracetools_test' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/tracetools_launch' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/ros2trace' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/tracetools_trace' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/tracetools_read' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/test_tracetools_launch' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/yeray/tracing_ws/install/test_tracetools' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.373s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/yeray/tracing_ws/install/test_tracetools' in the environment variable CMAKE_PREFIX_PATH doesn't exist
Starting >>> tracetools
--- stderr: tracetools                             
In file included from /usr/include/x86_64-linux-gnu/lttng/tracepoint-event.h:69,
                 from /home/yeray/tracing_ws/build/tracetools/include/tracetools/tp_call.h:443,
                 from /home/yeray/tracing_ws/src/ros2_tracing/tracetools/src/tp_call.c:18:
/home/yeray/tracing_ws/build/tracetools/include/tracetools/tp_call.h:421:5: error: static assertion failed: "Non-integer type `subs` not supported as element of LTTNG_UST_FIELD_ARRAY or LTTNG_UST_FIELD_SEQUENCE"
  421 |     ctf_sequence_hex(const void *, subs, subs_arg, size_t, num_subs_arg)
      |     ^~~~~~~~~~~~~~~~
/home/yeray/tracing_ws/build/tracetools/include/tracetools/tp_call.h:422:5: error: static assertion failed: "Non-integer type `pubs` not supported as element of LTTNG_UST_FIELD_ARRAY or LTTNG_UST_FIELD_SEQUENCE"
  422 |     ctf_sequence_hex(const void *, pubs, pubs_arg, size_t, num_pubs_arg)
      |     ^~~~~~~~~~~~~~~~
/home/yeray/tracing_ws/build/tracetools/include/tracetools/tp_call.h:436:5: error: static assertion failed: "Non-integer type `subs` not supported as element of LTTNG_UST_FIELD_ARRAY or LTTNG_UST_FIELD_SEQUENCE"
  436 |     ctf_sequence_hex(const void *, subs, subs_arg, size_t, num_subs_arg)
      |     ^~~~~~~~~~~~~~~~
/home/yeray/tracing_ws/build/tracetools/include/tracetools/tp_call.h:437:5: error: static assertion failed: "Non-integer type `pubs` not supported as element of LTTNG_UST_FIELD_ARRAY or LTTNG_UST_FIELD_SEQUENCE"
  437 |     ctf_sequence_hex(const void *, pubs, pubs_arg, size_t, num_pubs_arg)
      |     ^~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/tracetools.dir/build.make:104: CMakeFiles/tracetools.dir/src/tp_call.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:161: CMakeFiles/tracetools.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< tracetools [0.31s, exited with code 2]

Summary: 0 packages finished [0.65s]
  1 package failed: tracetools
  1 package had stderr output: tracetools
  

Is the issue likely caused by an incompatibility with ROS 2 Humble?

Is it possible to perform message flow analysis using the humble branch, or is it intended only for the message-link-instrumentation branch?

**Comment by christophebedard** [comment]
Sorry for the late response. That's an issue with LTTng, see https://bugs.lttng.org/issues/1355. It was [fixed in lttng-ust >=2.13.3](https://lists.lttng.org/pipermail/lttng-dev/2022-June/030193.html). I'm assuming you're using the version that Ubuntu Jammy 22.04 distributes, which is [`liblttng-ust-dev` 2.13.1](https://packages.ubuntu.com/jammy/liblttng-ust-dev). You could use the LTTng stable PPA to get a more recent version, see the instructions here: https://lttng.org/docs/v2.13/#doc-ubuntu-ppa.

**Comment by YerayGG** [comment]
It works, thanks.
